WV = WV or {}
WV.FileBuf = WV.FileBuf or {}
WV.PendingPath = nil
WV.CurrentBase = nil
WV.CurrentAddonLabel = nil
WV.CurrentWSID = nil
WV.WebView = nil
WV.WebReady = false
WV.PendingEvents = WV.PendingEvents or {}
WV.AddonCache = WV.AddonCache or {}
WV.CurrentSearch = nil
WV.Frame = nil
